#!/bin/bash

# exit on error
set -e

rm -f result.csv

# NUMNODES
for n in 8 16 32 64 128 256 512 1024 2048 4096 8192 16384
do

   /usr/local/common/gcc-7.3.0/bin/g++ proj1.c -o p1 -DNUMTRIES=32 -DNUMT=12 -DNUMNODES=$n -lm -fopenmp
   ./p1 &>> result.csv
   rm -f ./p1

done
